version: '3.8'

services:
  windows-monitor-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: windows-monitor-agent:latest
    container_name: windows-monitor-agent
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Монтируем Windows Event Logs (требуется для доступа к логам Windows)
      - type: bind
        source: C:/Windows/System32/winevt/Logs
        target: /winevt/Logs
        read_only: true
    environment:
      - TZ=Europe/Moscow
    # Конфигурация привилегий для доступа к системным компонентам Windows
    privileged: true
    networks:
      - monitor-network

  # Опциональный сервис для просмотра логов через веб-интерфейс
  log-viewer:
    image: amir20/dozzle:latest
    container_name: log-viewer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge 